Sprint 12: 
Aplicarás lo que has aprendido sobre APIs REST, métodos HTTP y códigos de estado, utilizando APIs públicas para consultar datos, filtrarlos y finalmente desarlas en un DataFrame de pandas.

Recursos:

Nivel 1:
{JSON} Placeholder

Nivel 2:
Try Public APIs for free

Nivel 3:
Open Data BCN

# Nivel 1: 
Desde un Jupyter Notebook harás los siguientes ejercicios utilizando la librería requests de Python.
Exploración básica con una API de laboratorio.

In [19]:
import requests
import pandas as pd 
from pprint import pprint                                          # Pretty Print

## 1.1:  Consulta la API pública JSONPlaceholder utilizando el método GET para obtener:

Lista de publicaciones (/posts)
Lista de usuarios (/users)
Lista de tareas (/todos)

sintaxis general petición -> respuesta JSON -> lista -> DataFrame: 

respuesta = requests.get(f"{url}/endpoint")   # Realiza una petición GET a la API.
datos = respuesta.json()                      # Convierte la respuesta JSON en una lista o diccionario de Python.
df = pd.DataFrame(datos)                      # Convierte los datos en un DataFrame de pandas.
display(df.head())                            # Muestra las 5 primeras filas del DataFrame.

In [20]:
url_1 = "https://jsonplaceholder.typicode.com"

respuesta_posts = requests.get(f"{url_1}/posts")
posts = respuesta_posts.json()
df_posts = pd.DataFrame(posts)
display(df_posts.head())

respuesta_users = requests.get(f"{url_1}/users")
users = respuesta_users.json()
df_users = pd.DataFrame(users)
display(df_users.head())

respuesta_todos = requests.get(f"{url_1}/todos")
todos = respuesta_todos.json()
df_todos = pd.DataFrame(todos)
display(df_todos.head())

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...

,id,name,username,email,address,phone,website,company
0,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,2,Ervin Howell,Antonette,Shanna@melissa.tv,"{'street': 'Victor Plains', 'suite': 'Suite 87...",010-692-6593 x09125,anastasia.net,"{'name': 'Deckow-Crist', 'catchPhrase': 'Proac..."
2,3,Clementine Bauch,Samantha,Nathan@yesenia.net,"{'street': 'Douglas Extension', 'suite': 'Suit...",1-463-123-4447,ramiro.info,"{'name': 'Romaguera-Jacobson', 'catchPhrase': ..."
3,4,Patricia Lebsack,Karianne,Julianne.OConner@kory.org,"{'street': 'Hoeger Mall', 'suite': 'Apt. 692',...",493-170-9623 x156,kale.biz,"{'name': 'Robel-Corkery', 'catchPhrase': 'Mult..."
4,5,Chelsey Dietrich,Kamren,Lucio_Hettinger@annie.ca,"{'street': 'Skiles Walks', 'suite': 'Suite 351...",(254)954-1289,demarco.info,"{'name': 'Keebler LLC', 'catchPhrase': 'User-c..."

   userId  id                                              title  completed
0       1   1                                 delectus aut autem      False
1       1   2                 quis ut nam facilis et officia qui      False
2       1   3                                fugiat veniam minus      False
3       1   4                                   et porro tempora       True
4       1   5  laboriosam mollitia et enim quasi adipisci qui...      False

## 1.2: Muestra por pantalla:

La cantidad total de cada recurso.
El código de estado de cada petición.

In [21]:
print(f"Código de estado: {respuesta_posts.status_code}")                  
print(f"Número de posts: {len(posts)}")                         
print(f"Código de estado: {respuesta_users.status_code}")   
print(f"Número de usuarios: {len(users)}")  
print(f"Código de estado: {respuesta_todos.status_code}") 
print(f"Número de tareas: {len(todos)}")

Código de estado: 200
Número de posts: 100
Código de estado: 200
Número de usuarios: 10
Código de estado: 200
Número de tareas: 200

## 1.3: Haz una petición a una publicación inexistente para obtener un error 404 y muestra el código de estado recibido.

In [22]:
respuesta_error = requests.get(url_1 + "/posts/inexistente")
print(f"Código de estado: {respuesta_error.status_code}")

Código de estado: 404

## 1.4:  Haz una petición POST para crear una nueva publicación ficticia. Incluye el título, el cuerpo del mensaje y un userId.

Muestra la respuesta JSON.
Muestra el código de estado.

In [23]:
nueva_publicacion = {
    "title": "Publicación número 1.",
    "body": "Probando la publicación con POST.",
    "userId": 1
}
respuesta_post = requests.post(f"{url_1}/posts",json=nueva_publicacion)

print(f"Código de estado: {respuesta_post.status_code}")
pprint(respuesta_post.json())

Código de estado: 201
{'body': 'Probando la publicación con POST.',
 'id': 101,
 'title': 'Publicación número 1.',
 'userId': 1}

## 1.5:  Haz una petición PATCH para modificar parcialmente una publicación existente.

Muestra la respuesta JSON.
Muestra el código de estado.

In [24]:
actualizacion = {"title": "Título actualizado con PATCH"}
respuesta_patch = requests.patch(f"{url_1}/posts/1",json=actualizacion)

print(f"Código de estado: {respuesta_patch.status_code}")
pprint(respuesta_patch.json())

Código de estado: 200
{'body': 'quia et suscipit\n'
         'suscipit recusandae consequuntur expedita et cum\n'
         'reprehenderit molestiae ut ut quas totam\n'
         'nostrum rerum est autem sunt rem eveniet architecto',
 'id': 1,
 'title': 'Título actualizado con PATCH',
 'userId': 1}

## 1.6: Haz una petición DELETE sobre una publicación.

Muestra la respuesta JSON.
Muestra el código de estado.

In [25]:
respuesta_delete = requests.delete(f"{url_1}/posts/1")

print(f"Código de estado: {respuesta_delete.status_code}")
pprint(respuesta_delete.json())

Código de estado: 200
{}

# Nivel 2
Preinscripción con una API pública real

## 2.1 Explora el repositorio de Public APIs y escoge una API que permita hacer peticiones GET.

### Selección de la API

Para la realización de esta práctica se ha seleccionado la API pública **CatFact** (`https://catfact.ninja`).

- Permite realizar peticiones mediante el método **GET** 
- Devuelve las respuestas en formato **JSON**  
- No requiere autenticación ni credenciales de acceso 

En este ejercicio se utiliza el endpoint **`/fact`**, que devuelve un hecho aleatorio sobre gatos en formato JSON.

In [26]:
url_2 = "https://catfact.ninja"

respuesta_fact = requests.get(f"{url_2}/fact")
print(f"Código de estado: {respuesta_fact.status_code}")

fact = respuesta_fact.json()
print(fact)

Código de estado: 200
{'fact': 'The Cat Fanciers Association (CFA) recognizes 44 breeds of cats.', 'length': 64}

## 2.2 Lee la documentación de la API
### 2.2.1 Revisa la sección de endpoints disponibles. En un markdown, apunta como mínimo dos endpoints diferentes.
### 2.2.2 Comprueba si ofrece filtros o parámetros opcionales interesantes. En un markdown, anotalos.

URL base: `https://catfact.ninja/`

En la documentación oficial de la API podemos encontrar los **endpoints** disponibles:

- /fact             devuelve una curiosidad aleatoria sobre gatos.
- /facts            devuelve una  paginada de curiosidades sobre gatos.
- /breeds           devuelve una  lista paginada de razas de gatos.

También podemos encontrar los parámetros disponibles, por ejemplo:

- limit             número de resultados por página.
- max_length        longitud máxima del texto de la curiosidad.

En el apartado de Responses se indica que las respuestas se devuelven en formato JSON (application/json).

En esta práctica se guarda la URL base en una variable y se realiza una petición GET al endpoint `/fact,obteniendo una curiosidad aleatoria sobre gatos en formato JSON.

### 2.2.3 Verifica que la respuesta sea en formato JSON (es el más adecuado para este ejercicio).

In [27]:
print(respuesta_fact.headers["Content-Type"])

application/json

## 2.3 Haz una petición GET sencilla:
### 2.3.1 Muestra el código de estado de la respuesta.

In [28]:
url = "https://catfact.ninja/fact"
respuesta = requests.get(url)

print(f"Código de estado: {respuesta.status_code}")

Código de estado: 200

### 2.3.2 Imprime de forma clara algunos de los campos de la respuesta JSON.

La respuesta recibida se convierte a formato JSON mediante el método response.json(). 
A continuación, se muestran de forma clara algunos de los campos devueltos por la API.

En este caso, el endpoint /fact devuelve principalmente el texto de la curiosidad (fact) y su longitud (length).

In [29]:
datos = respuesta_fact.json()

print("Curiosidad:")
print(datos["fact"])

print("\nLongitud:")
print(datos["length"])

Curiosidad:
The Cat Fanciers Association (CFA) recognizes 44 breeds of cats.

Longitud:
64

### 2.4  Convierte los datos a un DataFrame de pandas:
Como la respuesta contiene un único registro, se crea una lista con el diccionario antes de construir el DataFrame.

Muestra las primeras filas del DataFrame.

In [30]:
df_catfact = pd.DataFrame([datos])
df_catfact

                                                fact  length
0  The Cat Fanciers Association (CFA) recognizes ...      64

# Nivel 3
API de Open Data Barcelona

## 3.1 Utiliza la API de Open Data BCN para:
Buscar un dataset de tu interés mediante package_search y package_show. .

In [31]:
# url_3 = "https://opendata-ajuntament.barcelona.cat/ca/desenvolupadors#APIS"

url_3 = "https://opendata-ajuntament.barcelona.cat/data/api/3/action/package_search"

parametros_search = {
    "q": "bicicletes"
}

respuesta_search = requests.get(url_3, params=parametros_search)
print("Código de estado:", respuesta_search.status_code)

datos_search = respuesta_search.json()

print("Petición correcta:", datos_search["success"])
print("Datasets encontrados:", datos_search["result"]["count"])

for dataset in datos_search["result"]["results"][:5]:
    print(dataset["title"])

Código de estado: 200
Petición correcta: True
Datasets encontrados: 21
Friends of the Bike buildings of the public facilities of the city of Barcelona
Pacified streets of the city of Barcelona
Sidewalks ampliation in the city of Barcelona
Bike corridors of the city of Barcelona
Street laterals closed to traffic in the city of Barcelona

## 3.2 De los resultados obtenidos, selecciona uno que tenga recursos disponibles en CSV o JSON.

In [32]:
dataset = datos_search["result"]["results"][0]

url_show = "https://opendata-ajuntament.barcelona.cat/data/api/3/action/package_show"

parametros_show = {
    "id": dataset["id"]
}

respuesta_show = requests.get(url_show, params=parametros_show)

datos_show = respuesta_show.json()

print("Código de estado:", respuesta_show.status_code)
print("Petición correcta:", datos_show["success"])
print(dataset["title"])

Código de estado: 200
Petición correcta: True
Friends of the Bike buildings of the public facilities of the city of Barcelona

In [33]:
for recurso in datos_show["result"]["resources"]:
    print("Nombre:", recurso["name"])
    print("Formato:", recurso["format"])
    print("ID:", recurso["id"])
    print()

Nombre: 2025_edificis_amics_bici_bcn.csv
Formato: CSV
ID: 66fa1382-476a-459b-b0c0-c666112d1843

Nombre: 2025_edificis_amics_bici_bcn.geojson
Formato: GeoJSON
ID: b49637b9-f793-464c-9acb-0ea96495379f

Nombre: 2024_edificis_amics_bici_bcn.csv
Formato: CSV
ID: 619097da-d196-462d-b8da-34eb0182c7bc

Nombre: 2024_edificis_amics_bici_bcn_LONG.csv
Formato: CSV
ID: 336ba99e-f1df-4359-8f60-4ac3db4927ec

Nombre: 2024_edificis_amics_bici_bcn.geojson
Formato: GeoJSON
ID: 48321832-f30d-4279-af2a-80b328987d31

Nombre: 2023_edificis_amics_bici_bcn.csv
Formato: CSV
ID: 727a84af-d622-4362-b6d4-c21f2219456f

Nombre: 2023_edificis_amics_bici_bcn_long.csv
Formato: CSV
ID: 34a25480-7f40-41df-bb7e-4bef398bfabd

Nombre: 2023_edificis_amics_bici_bcn.geojson
Formato: GeoJSON
ID: 32d27f77-30f8-4875-9fd7-991c8c3aa48e

Nombre: 2022_edificis_amics_bici_bcn.csv
Formato: CSV
ID: b56c154c-0ca2-47c9-b65b-0eff6b364696

Nombre: 2022_edificis_amics_bici_bcn_long.csv
Formato: CSV
ID: c0e38b52-be36-4a74-bb3e-8bc479aac426

Nombre: 2022_edificis_amics_bici_bcn.geojson
Formato: GeoJSON
ID: 8b888dc1-3a0e-4c4f-963a-38aaa4cc8aa5

Nombre: 2021_edificis_amics_bici_bcn.csv
Formato: CSV
ID: 0ed57ca6-d32c-49c6-acd1-e1e8be0ea179

Nombre: 2021_edificis_amics_bici_bcn_long.csv
Formato: CSV
ID: f011bb70-8c20-46a1-9a79-345f2247e6af

Nombre: 2021_EDIFICIS_AMICS_BICI_BCN.geojson
Formato: GeoJSON
ID: 5eae1c79-9671-497a-b8c6-8823b6563056

Nombre: 2020_edificis_amics_bici_bcn.csv
Formato: CSV
ID: 8968421b-b12d-412f-a41a-a4d79ea89452

Nombre: 2020_edificis_amics_bici_bcn_LONG.csv
Formato: CSV
ID: e3dcf8d6-cfe5-48b3-96f2-174434a2e925

Nombre: 2020_EDIFICIS_AMICS_BICI_BCN.geojson
Formato: GeoJSON
ID: 3eb33f06-9228-4c46-a6fe-03921f422f51

## 3.3 Con el resource_id del recurso seleccionado, realiza una consulta mediante datastore_search por:

Recuperar al menos 100 registros.

In [34]:
resource_id = "336ba99e-f1df-4359-8f60-4ac3db4927ec"

url_datastore = "https://opendata-ajuntament.barcelona.cat/data/api/3/action/datastore_search"

parametros_datastore = {
    "resource_id": resource_id,
    "limit": 100
}

respuesta_datastore = requests.get(url_datastore, params=parametros_datastore)

datos_datastore = respuesta_datastore.json()

print("Código de estado:", respuesta_datastore.status_code)
print("Petición correcta:", datos_datastore["success"])
print("Registros recuperados:", len(datos_datastore["result"]["records"]))

Código de estado: 200
Petición correcta: True
Registros recuperados: 100

## 3.4 Convierte los resultados a un DataFrame.

In [35]:
df_bcn = pd.DataFrame(datos_datastore["result"]["records"])
df_bcn.head(2)

,Edifici,Latitud,Codi_Districte,Concepte,X_ETRS89,Nom_Districte,Numero_Via,Nom_Barri,Valor,Estat,Y_ETRS89,Codi_Barri,_id,Nom_Via,id,Longitud
0,Cases Consistorials,41.3819,1,Any_Auditoria,431230.34,Ciutat Vella,1,el Gòtic,2015,Edifici Amic de la Bici,4581482.742,2,1,Carrer dels gegants,1,2.1775
1,Seu de Districte Gràcia,41.4,6,Any_Auditoria,429602.19899999996,Gràcia,2,Vila de Gràcia,2015,Edifici Amic de la Bici,4583505.42,31,2,Plaça de la Vila de Gràcia,2,2.1578

## 3.5 Convierte el DataFrame en un fichero .csv.

In [36]:
df_bcn.to_csv("bicicletes.csv", index=False)
print("Fichero CSV guardado correctamente.")

Fichero CSV guardado correctamente.

fin sprint 12